services:
  opn-lic-srv:
    build: .
    container_name: open-license-server
    image: open-license-server:0.11.2025
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
      - ./lic/:/lic/
      - ./scp/:/scp/
      - ./bup/:/bup/
      - ./db/:/db/

    ports:
      - "8000:8000"

    restart: unless-stopped
